"""
Pydantic data models shared across the entire RAG system.

All domain objects are defined here. Import from this module
instead of creating local dataclasses or plain dicts.
"""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class SourceType(str, Enum):
    """File type of the original document."""

    TXT = "txt"
    MD = "md"
    HTML = "html"
    PY = "py"
    PDF = "pdf"
    PPTX = "pptx"


class ChunkStrategy(str, Enum):
    """Which chunking strategy was used to create a Chunk."""

    RECURSIVE = "recursive"
    HTML = "html"
    PYTHON = "python"
    SEMANTIC = "semantic"
    EXAMPLE = "example"
    VISUAL = "visual"  # Slide/page description generated by Vision LLM


# ---------------------------------------------------------------------------
# Ingestion models
# ---------------------------------------------------------------------------

class Document(BaseModel):
    """A raw document before chunking."""

    doc_id: str
    content: str
    source_file: str
    source_type: SourceType
    metadata: dict = Field(default_factory=dict)


class Chunk(BaseModel):
    """A document chunk ready for embedding and storage in Weaviate."""

    chunk_id: str
    doc_id: str
    content: str
    chunk_index: int
    chunk_strategy: ChunkStrategy
    source_file: str
    source_type: SourceType
    page_number: int | None = None    # Page/slide number for PDF/PPTX
    image_path: str | None = None     # Rendered image path (for UI display)
    embedding: list[float] | None = None
    metadata: dict = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# Retrieval models
# ---------------------------------------------------------------------------

class SearchResult(BaseModel):
    """A single retrieval result with relevance score."""

    chunk: Chunk
    score: float
    search_type: str  # "bm25", "semantic", "hybrid", "colbert"


class Citation(BaseModel):
    """
    A source citation in NotebookLM style.

    Stores the original text as-is rather than re-generating it,
    which helps prevent hallucinations.
    """

    citation_id: int
    source_file: str
    page_number: int | None = None
    original_text: str    # Original text as-is (not re-generated)
    relevance_score: float


# ---------------------------------------------------------------------------
# Agent / workflow models
# ---------------------------------------------------------------------------

class ValidationScores(BaseModel):
    """4-axis quality scores from the Validator (LLM-as-Judge)."""

    completeness: int   # 0-100: coverage of all enriched prompt requirements
    accuracy: int       # 0-100: consistency with citation source text
    relevance: int      # 0-100: alignment with the user's original intent
    faithfulness: int   # 0-100: whether content outside citations was generated
    average: float      # average of 4 scores (pass if >= 80)


class ValidationResult(BaseModel):
    """Output from the Validator agent."""

    scores: ValidationScores
    is_valid: bool              # average >= threshold
    reason: str                 # Reason for the decision (specific explanation of low-score items)
    missing_info: list[str] = Field(default_factory=list)  # Specific missing information


class ConversationTurn(BaseModel):
    """One turn in the chat history shown in the Streamlit UI."""

    role: str                   # "user", "facilitator", "synthesizer", "system"
    content: str
    citations: list[Citation] = Field(default_factory=list)
    validation: ValidationResult | None = None
    loop_count: int = 0


# ---------------------------------------------------------------------------
# Query / response models
# ---------------------------------------------------------------------------

class QueryRequest(BaseModel):
    """Incoming user query with optional search settings."""

    query: str
    use_colbert: bool = False
    metadata_filters: dict = Field(default_factory=dict)


class QueryResponse(BaseModel):
    """Final response returned to the Streamlit UI."""

    answer: str
    citations: list[Citation]
    enriched_prompt: str
    validation: ValidationResult | None = None
    loop_count: int = 0
